### ISSUE TITLE
End-of-break notification during running pomodoro

### ISSUE THREAD

**Issue by kindkaktus** [klemensschindler/tomatron#9]
When I start pomodoro before my break finishes, I still get "break finished, you can start pomodoro" notification when break time is over, regardless than I am already in pomodoro.

**Comment by klemensschindler** [comment]
Previously every time a pomodoro was stared, a new Java Timer object was created (there were some issues with reusing the same task object. 
Tomatron 1.2 uses a different kind of timer and only has one task instance. The issue should be fixed now. If you still encounter this issue, please re-open this item.
